broker: broker.cpp
	g++ --std=c++17 --std=c++17 -o broker broker.cpp

publisher: publisher.cpp
	g++ --std=c++17 -o publisher publisher.cpp

subscriber: subscriber.cpp
	g++ --std=c++17 -o subscriber subscriber.cpp

clean:
	rm -f *.o
	rm -f $(TARGET)
